from django.urls import path
from . import views

urlpatterns = [
    path('health/', views.health, name='health'),
    path('auth/register/', views.register, name='register'),
    path('auth/login/', views.login, name='login'),
    path('publications/', views.publications_feed, name='publications-feed'),
    path('publications/by-city/', views.publications_by_city, name='publications-by-city'),
    path('publications/<str:pub_id>/', views.get_publication_details, name='publication-details'),
    path('publications/<str:pub_id>/like/', views.like_publication, name='like-publication'),
    path('publications/<str:pub_id>/comment/', views.add_publication_comment, name='add-publication-comment'),
    path('publications/<str:pub_id>/comment/<str:comment_id>/reply/', views.add_publication_reply, name='add-publication-reply'),
    path('publications/<str:pub_id>/comment/<str:comment_id>/reaction/', views.add_publication_reaction, name='add-publication-reaction'),
    path('publications/<str:pub_id>/clone/', views.clone_publication, name='clone-publication'),
    path('plans/', views.plans_list, name='plans-list'),
     path('plans/create/', views.create_plan, name='create-plan'),
    path('plans/<str:plan_id>/', views.plan_detail, name='plan-detail'),
    path('plans/<str:plan_id>/like/', views.like_plan, name='like-plan'),
    path('plans/<str:plan_id>/comment/', views.add_comment, name='add-comment'),
    path('plans/<str:plan_id>/comment/<str:comment_id>/reply/', views.add_reply, name='add-reply'),
    path('plans/<str:plan_id>/comment/<str:comment_id>/reaction/', views.add_reaction, name='add-reaction'),
    path('plans/<str:plan_id>/clone/', views.clone_plan, name='clone-plan'),
    path('plans/<str:plan_id>/share/', views.share_plan, name='share-plan'),
    path('plans/<str:plan_id>/unshare/', views.unshare_plan, name='unshare-plan'),
    path('plans/<str:plan_id>/publish/', views.publish_plan, name='publish-plan'),
    path('plans/by-city/', views.plans_by_city, name='plans-by-city'),
    path('notifications/', views.create_notification, name='create-notification'),
    path('notifications/<str:user_id>/', views.user_notifications, name='user-notifications'),
    path('profile/<str:user_id>/private-plans/', views.user_private_plans, name='user-private-plans'),
    path('profile/<str:user_id>/cloned-plans/', views.user_cloned_plans, name='user-cloned-plans'),
    path('profile/<str:user_id>/follow/', views.follow_user, name='follow-user'),
    path('profile/<str:user_id>/unfollow/', views.unfollow_user, name='unfollow-user'),
    path('profile/<str:user_id>/remove-follower/', views.remove_follower, name='remove-follower'),
    path('profile/<str:user_id>/follow-status/', views.check_follow_status, name='follow-status'),
    path('profile/<str:user_id>/update/', views.update_user_profile, name='update-user-profile'),
    path('profile/<str:user_id>/sync-plans/', views.sync_publications_with_plans, name='sync-publications'),
    path('profile/<str:user_id>/', views.user_profile, name='user-profile'),
    path('users/', views.all_users, name='all-users'),
]
